set nobackup
set noswapfile
set noundofile
set number
set list
set expandtab
set softtabstop=4
set shiftwidth=4
set splitbelow
set splitright
set cursorline
set cursorcolumn
set shortmess-=S
let g:netrw_preview=1
let g:netrw_liststyle=3
let g:netrw_winsize=30
